version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    networks:
      - enrollment
    environment:
      - POSTGRES_PASSWORD=password
  postgres_db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./deploy/ueba.csv:/ueba.csv
      - ./deploy/createTable.sql:/docker-entrypoint-initdb.d/1-createTable.sql
      - ./deploy/fill.sql:/docker-entrypoint-initdb.d/2-fill.sql
    networks:
      - enrollment

networks:
  enrollment: